from typing import Optional, Protocol, runtime_checkable
from core.discovery.base import CliRecord
from core.capability.model import CapabilityRecord


@runtime_checkable
class LanguageAdapter(Protocol):
    def detect(self, rec: CliRecord) -> bool: ...
    def launch_spec(self, rec: CliRecord) -> dict: ...
    def health_cmd(self, rec: CliRecord) -> str: ...
    def infer_capability(self, rec: CliRecord) -> Optional[CapabilityRecord]: ...
